[package]
name = "integer_multiplication"
version = "0.1.0"
authors = ["Sebastien Marleau <smarleau.2019@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rand = "0.8.3"